/**
 * Round-trip parse/serialize tests for all 11 primitive types and ParserActions.
 *
 * Strategy: parse a string S, call getText(false) → T1, parse T1, call getText(false) → T2.
 * Assert T1 === T2 (stability). This proves the serialized form is self-consistent without
 * comparing against Java-generated byte output (which may use different float formatting).
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { DrawingModel } from '../../src/circuit/model/DrawingModel.js';
import { ParserActions } from '../../src/circuit/controllers/ParserActions.js';
import { StandardLayers } from '../../src/layers/StandardLayers.js';
import { Globals } from '../../src/globals/Globals.js';
import { MacroDesc } from '../../src/primitives/MacroDesc.js';

// ---------- helpers ----------

function makeModel(): DrawingModel {
    const m = new DrawingModel();
    m.setLayers(StandardLayers.createStandardLayers());
    return m;
}

function makeParser(model?: DrawingModel): ParserActions {
    return new ParserActions(model ?? makeModel());
}

/** Parse s → getText(false). */
function serialize(s: string): string {
    const pa = makeParser();
    pa.parseString(s);
    return pa.getText(false);
}

/**
 * Stability test: parse S → getText(false) → parse → getText(false).
 * The two serializations must be identical.
 */
function assertStable(s: string): string {
    const t1 = serialize(s);
    const t2 = serialize(t1);
    expect(t2).toBe(t1);
    return t1;
}

// Save/restore Globals so tests don't pollute each other.
let savedDiameter: number;
let savedLineWidth: number;
let savedLineWidthCircles: number;

beforeEach(() => {
    savedDiameter = Globals.diameterConnection;
    savedLineWidth = Globals.lineWidth;
    savedLineWidthCircles = Globals.lineWidthCircles;
});

afterEach(() => {
    Globals.diameterConnection = savedDiameter;
    Globals.lineWidth = savedLineWidth;
    Globals.lineWidthCircles = savedLineWidthCircles;
});

// ---------- PrimitiveLine ----------

describe('PrimitiveLine (LI)', () => {
    it('parses and re-serializes a basic line', () => {
        const out = assertStable('[FIDOCAD]\nLI 10 20 30 40 0\n');
        expect(out).toBe('LI 10 20 30 40 0\n');
    });

    it('preserves non-zero layer', () => {
        const out = assertStable('[FIDOCAD]\nLI 5 5 100 100 3\n');
        expect(out).toBe('LI 5 5 100 100 3\n');
    });

    it('produces empty output for zero-length line (no name/value)', () => {
        const out = serialize('[FIDOCAD]\nLI 50 50 50 50 0\n');
        expect(out).toBe('');
    });

    it('is stable from test size file', () => {
        assertStable('[FIDOCAD]\nFJC C 1.5\nFJC B 0.25\nLI 25 45 110 25 0\n');
    });

    it('round-trips multiple lines', () => {
        const input = '[FIDOCAD]\nLI 80 35 80 45 0\nLI 95 35 95 45 0\nLI 100 35 100 45 0\n';
        assertStable(input);
    });
});

// ---------- PrimitiveBezier ----------

describe('PrimitiveBezier (BE)', () => {
    it('parses and re-serializes a bezier curve', () => {
        const out = assertStable('[FIDOCAD]\nBE 50 5 20 60 70 35 50 70 0\n');
        expect(out).toBe('BE 50 5 20 60 70 35 50 70 0\n');
    });

    it('preserves layer on bezier', () => {
        const out = assertStable('[FIDOCAD]\nBE 10 20 30 40 50 60 70 80 2\n');
        expect(out).toBe('BE 10 20 30 40 50 60 70 80 2\n');
    });

    it('is stable from test size file', () => {
        assertStable('[FIDOCAD]\nFJC C 1.5\nFJC B 0.25\nBE 50 5 20 60 70 35 50 70 0\n');
    });
});

// ---------- PrimitiveRectangle ----------

describe('PrimitiveRectangle (RV/RP)', () => {
    it('parses empty rectangle RV', () => {
        const out = assertStable('[FIDOCAD]\nRV 25 20 95 75 0\n');
        expect(out).toBe('RV 25 20 95 75 0\n');
    });

    it('parses filled rectangle RP', () => {
        const out = assertStable('[FIDOCAD]\nRP 10 10 50 40 0\n');
        expect(out).toBe('RP 10 10 50 40 0\n');
    });

    it('preserves layer', () => {
        const out = assertStable('[FIDOCAD]\nRV 10 10 50 40 5\n');
        expect(out).toBe('RV 10 10 50 40 5\n');
    });

    it('is stable from test size file', () => {
        assertStable('[FIDOCAD]\nFJC C 1.5\nFJC B 0.25\nRV 25 20 95 75 0\n');
    });
});

// ---------- PrimitiveOval ----------

describe('PrimitiveOval (EV/EP)', () => {
    it('parses empty oval EV', () => {
        const out = assertStable('[FIDOCAD]\nEV 45 15 95 65 0\n');
        expect(out).toBe('EV 45 15 95 65 0\n');
    });

    it('parses filled oval EP', () => {
        const out = assertStable('[FIDOCAD]\nEP 10 10 40 40 0\n');
        expect(out).toBe('EP 10 10 40 40 0\n');
    });

    it('is stable from test size file', () => {
        assertStable('[FIDOCAD]\nFJC C 1.5\nFJC B 0.25\nEV 45 15 95 65 0\n');
    });
});

// ---------- PrimitivePolygon ----------

describe('PrimitivePolygon (PV/PP)', () => {
    it('parses open polygon PV', () => {
        const out = assertStable('[FIDOCAD]\nPV 25 50 65 25 50 85 100 35 100 75 0\n');
        // polygon toString appends a trailing space before layer
        expect(out).toContain('PV ');
        expect(out).toContain('25 50 ');
        expect(out).toContain(' 0\n');
    });

    it('parses filled polygon PP', () => {
        const out = assertStable('[FIDOCAD]\nPP 10 20 30 40 50 60 0\n');
        expect(out).toContain('PP ');
    });

    it('is stable from test size file', () => {
        assertStable('[FIDOCAD]\nFJC C 1.5\nFJC B 0.25\nPV 25 50 65 25 50 85 100 35 100 75 0\n');
    });
});

// ---------- PrimitiveComplexCurve ----------

describe('PrimitiveComplexCurve (CV/CP)', () => {
    it('parses closed filled curve CP', () => {
        const input = '[FIDOCAD]\nCP 1 45 45 70 30 45 60 80 50 75 65 95 30 20 30 65 75 0\n';
        const out = assertStable(input);
        expect(out).toContain('CP ');
        expect(out).toContain('1 ');
    });

    it('parses open unfilled curve CV', () => {
        const input = '[FIDOCAD]\nCV 0 170 130 195 135 200 110 240 115 245 140 215 145 195 100 0\n';
        const out = assertStable(input);
        expect(out).toContain('CV ');
        expect(out).toContain('0 ');
    });

    it('is stable from test size file (open curve)', () => {
        assertStable('[FIDOCAD]\nFJC C 1.5\nFJC A 0.35\nFJC B 0.25\n' +
            'CP 1 45 45 70 30 45 60 80 50 75 65 95 30 20 30 65 75 0\n');
    });

    it('roundtrips a short CV', () => {
        const input = '[FIDOCAD]\nCV 0 240 5 260 25 240 30 0\n';
        const out = assertStable(input);
        expect(out).toBe('CV 0 240 5 260 25 240 30 0\n');
    });
});

// ---------- PrimitivePCBPad ----------

describe('PrimitivePCBPad (PA)', () => {
    it('parses a PCB pad with oval style', () => {
        const out = assertStable('[FIDOCAD]\nPA 50 40 10 10 5 0 0\n');
        expect(out).toBe('PA 50 40 10 10 5 0 0\n');
    });

    it('parses a PCB pad with rect style', () => {
        const out = assertStable('[FIDOCAD]\nPA 30 135 10 10 2 1 0\n');
        expect(out).toBe('PA 30 135 10 10 2 1 0\n');
    });

    it('parses a PCB pad with rounded rect style', () => {
        const out = assertStable('[FIDOCAD]\nPA 45 135 10 10 2 2 0\n');
        expect(out).toBe('PA 45 135 10 10 2 2 0\n');
    });

    it('is stable from test size file', () => {
        assertStable('[FIDOCAD]\nFJC C 1.5\nFJC B 0.25\nPA 50 40 10 10 5 0 0\n');
    });

    it('preserves layer', () => {
        const out = assertStable('[FIDOCAD]\nPA 100 100 8 8 4 0 3\n');
        expect(out).toBe('PA 100 100 8 8 4 0 3\n');
    });
});

// ---------- PrimitivePCBLine ----------

describe('PrimitivePCBLine (PL)', () => {
    it('parses a PCB line with integer width', () => {
        const out = assertStable('[FIDOCAD]\nPL 10 110 90 110 5 0\n');
        expect(out).toBe('PL 10 110 90 110 5 0\n');
    });

    it('parses a PCB line with different widths', () => {
        assertStable('[FIDOCAD]\nPL 10 90 90 90 3 0\nPL 10 100 90 100 4 0\n');
    });

    it('preserves layer', () => {
        const out = assertStable('[FIDOCAD]\nPL 180 260 235 285 2 2\n');
        // roundIntelligently(2) = '2' (integer)
        expect(out).toBe('PL 180 260 235 285 2 2\n');
    });

    it('is stable from test size file', () => {
        assertStable('[FIDOCAD]\nFJC C 1.5\nFJC B 0.25\nPL 10 110 90 110 5 0\n');
    });
});

// ---------- PrimitiveConnection ----------

describe('PrimitiveConnection (SA)', () => {
    it('parses a connection dot', () => {
        const out = assertStable('[FIDOCAD]\nSA 70 60 0\n');
        expect(out).toBe('SA 70 60 0\n');
    });

    it('parses multiple connections', () => {
        const input = '[FIDOCAD]\nSA 70 60 0\nSA 70 65 0\nSA 80 60 0\n';
        assertStable(input);
    });

    it('preserves layer', () => {
        const out = assertStable('[FIDOCAD]\nSA 50 50 3\n');
        expect(out).toBe('SA 50 50 3\n');
    });

    it('is stable from test size file', () => {
        assertStable('[FIDOCAD]\nFJC C 1.5\nFJC B 0.25\nSA 50 50 0\n');
    });
});

// ---------- PrimitiveAdvText ----------

describe('PrimitiveAdvText (TY/TE)', () => {
    it('parses TY with default font (*)', () => {
        const out = assertStable('[FIDOCAD]\nTY 85 25 5 3 0 0 0 * A\n');
        expect(out).toBe('TY 85 25 5 3 0 0 0 * A\n');
    });

    it('parses TY with named font', () => {
        const out = assertStable('[FIDOCAD]\nTY 35 35 4 3 0 0 0 Helvetica This is a test\n');
        expect(out).toBe('TY 35 35 4 3 0 0 0 Helvetica This is a test\n');
    });

    it('converts TE to TY on output', () => {
        const pa = makeParser();
        pa.parseString('[FIDOCAD]\nTE 10 20 Hello\n');
        const out = pa.getText(false);
        // TE → TY conversion: siy=4, six=3, o=0, sty=0, layer=0
        expect(out).toContain('TY 10 20 4 3 0 0 0 *');
        expect(out).toContain('Hello');
    });

    it('TY output is stable (TY → TY, not TE)', () => {
        // After one parse of TE, output is TY. TY is then stable.
        const pa = makeParser();
        pa.parseString('[FIDOCAD]\nTE 10 20 Hello\n');
        const t1 = pa.getText(false);
        const t2 = serialize(t1);
        expect(t2).toBe(t1);
    });

    it('preserves orientation', () => {
        const out = assertStable('[FIDOCAD]\nTY 225 40 8 3 20 0 0 * Text\n');
        expect(out).toBe('TY 225 40 8 3 20 0 0 * Text\n');
    });

    it('preserves style flags', () => {
        // sty=4 = bold
        const out = assertStable('[FIDOCAD]\nTY 220 10 4 3 0 4 0 * Text\n');
        expect(out).toBe('TY 220 10 4 3 0 4 0 * Text\n');
    });

    it('handles multi-word text', () => {
        const out = assertStable('[FIDOCAD]\nTY 100 100 4 3 0 0 0 * Hello World Foo Bar\n');
        expect(out).toBe('TY 100 100 4 3 0 0 0 * Hello World Foo Bar\n');
    });

    it('is stable from test size file', () => {
        assertStable('[FIDOCAD]\nFJC C 1.5\nFJC B 0.25\nTY 35 35 4 3 0 0 0 Helvetica This is a test\n');
    });
});

// ---------- PrimitiveMacro ----------

describe('PrimitiveMacro (MC)', () => {
    function makeModelWithMacro(key: string, description: string): DrawingModel {
        const model = makeModel();
        const lib = model.getLibrary();
        lib.set(key, new MacroDesc(key, key, description, 'test', 'testlib', 'test.fcl'));
        return model;
    }

    it('parses a macro and re-serializes its key', () => {
        const model = makeModelWithMacro('testmacro', '[FIDOCAD]\nLI 0 0 10 10 0\n');
        const pa = makeParser(model);
        pa.parseString('[FIDOCAD]\nMC 100 100 0 0 testmacro\n');
        const out = pa.getText(false);
        expect(out).toBe('MC 100 100 0 0 testmacro\n');
    });

    it('preserves orientation', () => {
        const model = makeModelWithMacro('mypart', '[FIDOCAD]\nLI 0 0 5 5 0\n');
        const pa = makeParser(model);
        pa.parseString('[FIDOCAD]\nMC 50 50 2 0 mypart\n');
        const out = pa.getText(false);
        expect(out).toBe('MC 50 50 2 0 mypart\n');
    });

    it('preserves mirror flag', () => {
        const model = makeModelWithMacro('widget', '[FIDOCAD]\nLI 0 0 5 5 0\n');
        const pa = makeParser(model);
        pa.parseString('[FIDOCAD]\nMC 30 40 1 1 widget\n');
        const out = pa.getText(false);
        expect(out).toBe('MC 30 40 1 1 widget\n');
    });

    it('is stable (parse → getText → parse → getText)', () => {
        const description = '[FIDOCAD]\nLI 0 0 10 10 0\n';
        const model1 = makeModelWithMacro('part', description);
        const pa1 = makeParser(model1);
        pa1.parseString('[FIDOCAD]\nMC 20 30 0 0 part\n');
        const t1 = pa1.getText(false);

        const model2 = makeModelWithMacro('part', description);
        const pa2 = makeParser(model2);
        pa2.parseString(t1);
        const t2 = pa2.getText(false);

        expect(t2).toBe(t1);
    });

    it('silently skips unknown macros (no library entry)', () => {
        const pa = makeParser();
        // Should not throw; the unknown macro is silently dropped.
        expect(() => pa.parseString('[FIDOCAD]\nMC 80 35 0 0 unknown_macro\n')).not.toThrow();
    });
});

// ---------- Full document stability ----------

describe('Full document stability', () => {
    it('is stable for individual line primitives', () => {
        assertStable('[FIDOCAD]\nLI 25 45 110 25 0\n');
    });

    it('is stable for individual bezier', () => {
        assertStable('[FIDOCAD]\nBE 50 5 20 60 70 35 50 70 0\n');
    });

    it('is stable for a document with mixed primitives (no FCJ)', () => {
        const doc = [
            '[FIDOCAD]',
            'LI 10 10 100 10 0',
            'LI 100 10 100 100 0',
            'RV 10 10 50 50 0',
            'RP 60 60 90 90 0',
            'EV 20 20 40 40 0',
            'EP 50 50 80 80 0',
            'BE 10 90 30 70 70 70 90 90 0',
            'PV 10 10 50 10 50 50 10 50 0',
            'PP 60 10 100 10 100 50 60 50 0',
            'CV 0 10 10 30 20 50 10 0',
            'CP 1 70 10 90 20 90 40 70 50 0',
            'SA 30 30 0',
            'PL 10 60 100 60 3 0',
            'PA 50 80 8 8 3 0 0',
            'TY 10 5 4 3 0 0 0 * Label',
            '',
        ].join('\n');
        assertStable(doc);
    });

    it('is stable for test_pattern.fcd (strips FCJ, all base primitives present)', () => {
        // test_pattern.fcd without the [FIDOCAD] header and with inline content.
        // We use assertStable which checks getText(false) is idempotent.
        const doc = `[FIDOCAD]
LI 5 50 90 50 0
LI 5 45 90 45 0
LI 5 40 90 40 0
EP 5 5 15 15 0
EV 20 5 30 15 0
EV 50 5 60 15 0
EV 65 5 75 15 0
EV 80 5 90 15 0
RP 5 20 15 30 0
RV 20 20 30 30 0
RV 50 20 60 30 0
RV 65 20 75 30 0
RV 80 20 90 30 0
LI 100 5 185 5 0
LI 100 15 185 15 0
LI 100 20 185 20 0
LI 100 25 185 25 0
LI 100 35 185 35 0
LI 100 40 185 40 0
LI 100 45 185 45 0
LI 100 55 185 55 0
LI 100 60 185 60 0
LI 100 65 185 65 0
LI 100 75 185 75 0
LI 100 80 185 80 0
BE 15 80 10 55 50 55 35 85 0
BE 25 80 20 55 60 55 45 85 0
BE 30 80 25 55 65 55 50 85 0
BE 35 80 30 55 70 55 55 85 0
SA 70 60 0
SA 70 65 0
SA 80 60 0
SA 80 65 0
SA 80 70 0
SA 70 70 0
PL 10 110 90 110 5 0
PL 10 120 90 120 6 0
PL 10 90 90 90 3 0
PL 10 100 90 100 4 0
RP 100 85 110 95 0
PA 15 135 10 10 2 0 0
PA 30 135 10 10 2 1 0
PA 45 135 10 10 2 2 0
BE 130 125 50 150 135 175 80 125 0
BE 145 125 65 150 150 175 95 125 0
PP 0 165 45 150 0 185 50 160 0
PV 40 165 85 150 40 185 90 160 0
PV 120 165 165 150 120 185 170 160 0
PV 160 165 205 150 160 185 210 160 0
PV 200 165 245 150 200 185 250 160 0
TY 220 10 4 3 0 0 0 * Text
TY 220 10 4 3 0 4 0 * Text
TY 220 20 4 8 0 0 0 * Text
TY 220 20 4 8 0 4 0 * Text
TY 220 25 8 3 0 0 0 * Text
TY 220 25 8 3 0 4 0 * Text
TY 220 35 8 3 0 0 0 * Text
TY 225 40 8 3 20 0 0 * Text
TY 230 45 8 3 40 0 0 * Text
TY 235 50 8 3 60 0 0 * Text
TY 240 55 8 3 80 0 0 * Text
TY 245 60 8 3 90 0 0 * Text
TY 215 40 8 3 20 4 0 * Text
TY 210 45 8 3 40 4 0 * Text
TY 205 50 8 3 60 4 0 * Text
TY 200 55 8 3 80 4 0 * Text
TY 220 35 8 3 0 4 0 * Text
TY 195 60 8 3 90 4 0 * Text
EV 200 60 215 70 0
EV 225 60 240 70 0
EV 215 70 225 80 0
BE 205 80 215 90 225 90 235 80 0
BE 190 60 195 115 245 110 250 60 0
EP 205 65 210 70 0
EP 230 65 235 70 0
TY 230 130 4 3 0 4 0 * Text
TY 230 130 4 3 90 4 0 * Text
TY 230 130 4 3 180 4 0 * Text
TY 230 130 4 3 270 4 0 * Text
CV 0 170 130 195 135 200 110 240 115 245 140 215 145 195 100 0
CP 1 125 150 135 135 175 145 145 130 135 150 0
CV 0 70 80 90 80 100 105 115 125 105 105 0
CV 0 240 5 260 25 240 30 0
`;
        assertStable(doc);
    });

    it('primitive count is correct after parsing', () => {
        const pa = makeParser();
        pa.parseString('[FIDOCAD]\nLI 1 1 2 2 0\nRV 3 3 4 4 0\nEV 5 5 6 6 0\n');
        const primitives = pa['model'].getPrimitiveVector();
        expect(primitives).toHaveLength(3);
    });
});

// ---------- FJC configuration ----------

describe('FJC configuration parsing', () => {
    it('FJC C changes diameterConnection', () => {
        const pa = makeParser();
        pa.parseString('[FIDOCAD]\nFJC C 2.5\n');
        expect(Globals.diameterConnection).toBeCloseTo(2.5);
    });

    it('FJC A changes lineWidth', () => {
        const pa = makeParser();
        pa.parseString('[FIDOCAD]\nFJC A 0.5\n');
        expect(Globals.lineWidth).toBeCloseTo(0.5);
    });

    it('FJC B changes lineWidthCircles', () => {
        const pa = makeParser();
        pa.parseString('[FIDOCAD]\nFJC B 0.25\n');
        expect(Globals.lineWidthCircles).toBeCloseTo(0.25);
    });
});

// ---------- FCJ extension tokens ----------

describe('FCJ extension tokens', () => {
    it('line with FCJ arrow+dash parses without error', () => {
        const input = '[FIDOCAD]\nLI 5 50 90 50 0\nFCJ 0 0 3 2 4 0\n';
        const pa = makeParser();
        expect(() => pa.parseString(input)).not.toThrow();
        // Without extensions=true output, FCJ data is lost but primitive is still there.
        const out = pa.getText(false);
        expect(out).toBe('LI 5 50 90 50 0\n');
    });

    it('bezier with FCJ dash parses without error', () => {
        const input = '[FIDOCAD]\nBE 25 80 20 55 60 55 45 85 0\nFCJ 0 0 0 0 2 0\n';
        const pa = makeParser();
        expect(() => pa.parseString(input)).not.toThrow();
        const out = pa.getText(false);
        expect(out).toBe('BE 25 80 20 55 60 55 45 85 0\n');
    });

    it('rectangle with FCJ fill type parses without error', () => {
        const input = '[FIDOCAD]\nRV 50 20 60 30 0\nFCJ 2 0\n';
        const pa = makeParser();
        expect(() => pa.parseString(input)).not.toThrow();
    });

    it('oval with FCJ fill type parses without error', () => {
        const input = '[FIDOCAD]\nEV 50 5 60 15 0\nFCJ 2 0\n';
        const pa = makeParser();
        expect(() => pa.parseString(input)).not.toThrow();
    });

    it('polygon with FCJ fill type parses without error', () => {
        const input = '[FIDOCAD]\nPV 40 165 85 150 40 185 90 160 0\nFCJ 2 0\n';
        const pa = makeParser();
        expect(() => pa.parseString(input)).not.toThrow();
    });

    it('complex curve with FCJ parses without error', () => {
        const input = '[FIDOCAD]\nCV 0 70 80 90 80 100 105 115 125 105 105 0\nFCJ 3 0 3 2 0 0\n';
        const pa = makeParser();
        expect(() => pa.parseString(input)).not.toThrow();
    });
});

// ---------- addString (incremental parse) ----------

describe('ParserActions.addString', () => {
    it('addString appends to existing primitives', () => {
        const model = makeModel();
        const pa = makeParser(model);
        pa.parseString('[FIDOCAD]\nLI 1 1 2 2 0\n');
        pa.addString('[FIDOCAD]\nRV 3 3 4 4 0\n', false);
        expect(model.getPrimitiveVector()).toHaveLength(2);
    });

    it('parseString clears previous primitives', () => {
        const model = makeModel();
        const pa = makeParser(model);
        pa.parseString('[FIDOCAD]\nLI 1 1 2 2 0\nRV 3 3 4 4 0\n');
        pa.parseString('[FIDOCAD]\nSA 10 10 0\n');
        expect(model.getPrimitiveVector()).toHaveLength(1);
    });
});

// ---------- library round-trip ----------

describe('readLibraryString', () => {
    it('loads a simple library and makes macro parseable', () => {
        const model = makeModel();
        const pa = makeParser(model);
        const libContent = `
{Electronics}
[RLED RLED - Red LED
LI 0 0 10 0 0
LI 10 0 20 0 0
]
`;
        pa.readLibraryString(libContent, 'electronics');
        const lib = model.getLibrary();
        // Key format: prefix.macroname (lowercased)
        const hasLED = [...lib.keys()].some(k => k.includes('rled'));
        expect(hasLED).toBe(true);
    });
});
